#ifndef RIVER_H
#define RIVER_H

#include "game.h"

// gators
#define GATOR_HEIGHT BLOCK_SIZE
#define GATOR_LENGTH BLOCK_SIZE*3
// logs
#define LOG_HEIGHT BLOCK_SIZE
#define LOG_MIN_LENGTH BLOCK_SIZE*3
#define LOG_MAX_LENGTH BLOCK_SIZE*6
// river lanes
#define RIVER_LANE_SIZE BLOCK_SIZE
#define RIVER_LANE_1 RIVER_LANE_SIZE * 1
#define RIVER_LANE_2 RIVER_LANE_SIZE * 3
#define RIVER_LANE_3 RIVER_LANE_SIZE * 5
#define RIVER_LANE_4 RIVER_LANE_SIZE * 7
// river lanes speed
#define RIVER_LANE_1_SPEED 1
#define RIVER_LANE_2_SPEED 2
#define RIVER_LANE_3_SPEED 1
#define RIVER_LANE_4_SPEED 2
#define RIVER_MAX_SPEED 3
#define RIVER_MIN_SPEED 1
// river boundaries
#define RIVER_UPPER_BOUNDARY 2*LANE_SIZE
#define RIVER_LOWER_BOUNDARY WINDOW_HEIGHT/2 - 3*LANE_SIZE

#endif